version: "3.8"

services:
  app:
    image: ruby:2.7
    container_name: rails_app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ".:/usr/src/app"
    command: ["rails", "server", "-b", "0.0.0.0"]
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
